{
  "mixed-port": 7890,
  "allow-lan": false,
  "unified-delay": false,
  "log-level": "silent",
  "mode": "rule",
  "tcp-concurrent": true,
  "geo-auto-update": true,
  "geo-update-interval": 168,
  "external-controller": "127.0.0.1:9090",
  "external-ui": "ui",
  "profile": {
    "store-selected": true,
    "store-fake-ip": true
  },
  "tun": {
    "enable": true,
    "stack": "mixed",
    "auto-route": true,
    "strict-route": true,
    "auto-detect-interface": true,
    "dns-hijack": [
      "any:53",
      "tcp://any:53"
    ],
    "mtu": 9000
  },
  "sniffer": {
    "enable": true,
    "force-dns-mapping": true,
    "parse-pure-ip": true,
    "override-destination": true,
    "sniff": {
      "HTTP": {
        "ports": [
          80,
          8080
        ]
      },
      "TLS": {
        "ports": [
          443,
          8443,
          2053,
          2083,
          2087,
          2096
        ]
      }
    }
  },
  "dns": {
    "enable": true,
    "respect-rules": true,
    "use-system-hosts": false,
    "listen": "127.0.0.1:1053",
    "ipv6": false,
    "nameserver": [
      "https://8.8.8.8/dns-query#✅ Anonymous Multi"
    ],
    "proxy-server-nameserver": [
      "8.8.8.8#DIRECT"
    ],
    "direct-nameserver": [
      "8.8.8.8#DIRECT"
    ],
    "direct-nameserver-follow-policy": true,
    "nameserver-policy": {
      "rule-set:geosite-ir": "8.8.8.8#DIRECT"
    },
    "enhanced-mode": "fake-ip",
    "fake-ip-range": "198.18.0.1/16",
    "fake-ip-filter-mode": "blacklist",
    "fake-ip-filter": [
      "+.lan",
      "+.local"
    ]
  },
  "proxies": [
    {
      "name": "🇵🇭 3 - PH - Trojan/TLS/UTLS - 2398",
      "type": "trojan",
      "server": "flb06181447.tmdsb.org",
      "port": 2398,
      "password": "3632736327",
      "sni": "flb06181447.tmdsb.org",
      "skip-cert-verify": false
    },
    {
      "name": "🇵🇭 4 - PH - Trojan/TLS/UTLS - 2398",
      "type": "trojan",
      "server": "flb06181447.tmdsb.org",
      "port": 2398,
      "password": "3632736327",
      "sni": "flb06181447.tmdsb.org",
      "skip-cert-verify": false
    },
    {
      "name": "🇰🇷 5 - KR - Trojan/TLS/UTLS - 2648",
      "type": "trojan",
      "server": "kr04212339.tmdsb.org",
      "port": 2648,
      "password": "3632736327",
      "sni": "kr04212339.tmdsb.org",
      "skip-cert-verify": false
    },
    {
      "name": "🇭🇺 24 - HU - Trojan/TLS/UTLS - 4443",
      "type": "trojan",
      "server": "hu2.vpnjantit.com",
      "port": 4443,
      "password": "C0ldyfh-vpnjantit.com",
      "sni": "hu2.vpnjantit.com",
      "skip-cert-verify": false
    },
    {
      "name": "🇮🇪 43 - IE - Trojan/TLS - 443",
      "type": "trojan",
      "server": "singular-lark.rooster465.autos",
      "port": 443,
      "password": "XG59623478",
      "sni": "singular-lark.rooster465.autos",
      "skip-cert-verify": false
    },
    {
      "name": "🇫🇷 57 - FR - Trojan/WS/TLS/UTLS - 443",
      "type": "trojan",
      "server": "81.255.155.10",
      "port": 443,
      "password": "humanity",
      "sni": "www.creationlong.org",
      "skip-cert-verify": false,
      "network": "ws",
      "ws-opts": {
        "path": "/assignment",
        "headers": {
          "Host": "www.creationlong.org"
        }
      }
    },
    {
      "name": "🇺🇸 61 - US - Trojan/WS/TLS/UTLS - 443",
      "type": "trojan",
      "server": "www.ignitelimit.com",
      "port": 443,
      "password": "humanity",
      "sni": "www.ignitelimit.com",
      "skip-cert-verify": false,
      "network": "ws",
      "ws-opts": {
        "path": "/assignment",
        "headers": {
          "Host": "www.ignitelimit.com"
        }
      }
    },
    {
      "name": "🇳🇱 4 - NL - VLESS/REALITY/PBK/SID/VISION - 40443",
      "type": "vless",
      "server": "netraidly.ru",
      "port": 40443,
      "uuid": "4480161e-2c59-4d37-8736-675c9af32bf1",
      "network": "tcp",
      "tls": true,
      "servername": "deepl.com",
      "skip-cert-verify": false,
      "client-fingerprint": ""
    },
    {
      "name": "🇸🇪 6 - SE - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "swed1.helper-internet.com",
      "port": 443,
      "uuid": "59da5351-5151-417d-b2f7-6923848b717e",
      "network": "tcp",
      "tls": true,
      "servername": "swed1.helper-internet.com",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome"
    },
    {
      "name": "🇷🇺 15 - RU - VLESS/TLS/VISION/UTLS - 443",
      "type": "vless",
      "server": "fast_s89.screw.page",
      "port": 443,
      "uuid": "c0aa0cee-e855-4bcc-9afc-46241cb17990",
      "network": "tcp",
      "tls": true,
      "servername": "fast_s89.screw.page",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 14 - US - VLESS/REALITY/PBK/VISION - 443",
      "type": "vless",
      "server": "meowfin.nethcloud.top",
      "port": 443,
      "uuid": "a34b5e88-cf0d-4c01-8199-2d1002d3c787",
      "network": "tcp",
      "tls": true,
      "servername": "www.wikihow.com",
      "skip-cert-verify": false,
      "client-fingerprint": ""
    },
    {
      "name": "🇺🇸 18 - US - VLESS/GRPC/TLS/UTLS - 443",
      "type": "vless",
      "server": "all.tellmethetrue.shop",
      "port": 443,
      "uuid": "e4824193-4f54-453b-d037-88368e85ef0e",
      "network": "grpc",
      "tls": true,
      "servername": "sca35.afterdomain.shop",
      "skip-cert-verify": false,
      "client-fingerprint": "random",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 1 - US - VMess/WS/TLS - 8444",
      "type": "vmess",
      "server": "45.205.31.175",
      "port": 8444,
      "uuid": "f1fb546a-eaaf-4c10-98f1-871b48931077",
      "alterId": 0,
      "cipher": "auto",
      "network": "ws",
      "ws-opts": {
        "path": "/warp",
        "headers": {
          "Host": "vpn.cyedu.xyz"
        }
      },
      "tls": true,
      "servername": "vpn.cyedu.xyz",
      "skip-cert-verify": false,
      "client-fingerprint": "",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 3 - US - VMess/WS/TLS - 443",
      "type": "vmess",
      "server": "45.205.31.175",
      "port": 443,
      "uuid": "79e0df31-8ed5-4213-9fff-292a9fbeae7b",
      "alterId": 0,
      "cipher": "auto",
      "network": "ws",
      "ws-opts": {
        "path": "/ws",
        "headers": {
          "Host": "vpn.cyedu.xyz"
        }
      },
      "tls": true,
      "servername": "vpn.cyedu.xyz",
      "skip-cert-verify": false,
      "client-fingerprint": "",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 6 - US - VMess/TLS - 10086",
      "type": "vmess",
      "server": "45.205.31.175",
      "port": 10086,
      "uuid": "33f38758-81d2-43b0-a74a-2d7c70ea27c8",
      "alterId": 0,
      "cipher": "auto",
      "network": "tcp",
      "tls": true,
      "servername": "vpn.cyedu.xyz",
      "skip-cert-verify": false,
      "client-fingerprint": "",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 5 - US - VMess/TLS/UTLS - 10086",
      "type": "vmess",
      "server": "45.205.31.175",
      "port": 10086,
      "uuid": "33f38758-81d2-43b0-a74a-2d7c70ea27c8",
      "alterId": 0,
      "cipher": "auto",
      "network": "tcp",
      "tls": true,
      "servername": "vpn.cyedu.xyz",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    }
  ],
  "proxy-groups": [
    {
      "name": "✅ Anonymous Multi",
      "type": "select",
      "proxies": [
        "🚀 Best Ping",
        "🇵🇭 3 - PH - Trojan/TLS/UTLS - 2398",
        "🇵🇭 4 - PH - Trojan/TLS/UTLS - 2398",
        "🇰🇷 5 - KR - Trojan/TLS/UTLS - 2648",
        "🇭🇺 24 - HU - Trojan/TLS/UTLS - 4443",
        "🇮🇪 43 - IE - Trojan/TLS - 443",
        "🇫🇷 57 - FR - Trojan/WS/TLS/UTLS - 443",
        "🇺🇸 61 - US - Trojan/WS/TLS/UTLS - 443",
        "🇳🇱 4 - NL - VLESS/REALITY/PBK/SID/VISION - 40443",
        "🇸🇪 6 - SE - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇷🇺 15 - RU - VLESS/TLS/VISION/UTLS - 443",
        "🇺🇸 14 - US - VLESS/REALITY/PBK/VISION - 443",
        "🇺🇸 18 - US - VLESS/GRPC/TLS/UTLS - 443",
        "🇺🇸 1 - US - VMess/WS/TLS - 8444",
        "🇺🇸 3 - US - VMess/WS/TLS - 443",
        "🇺🇸 6 - US - VMess/TLS - 10086",
        "🇺🇸 5 - US - VMess/TLS/UTLS - 10086",
        "DIRECT"
      ]
    },
    {
      "name": "🚀 Best Ping",
      "type": "url-test",
      "proxies": [
        "🇵🇭 3 - PH - Trojan/TLS/UTLS - 2398",
        "🇵🇭 4 - PH - Trojan/TLS/UTLS - 2398",
        "🇰🇷 5 - KR - Trojan/TLS/UTLS - 2648",
        "🇭🇺 24 - HU - Trojan/TLS/UTLS - 4443",
        "🇮🇪 43 - IE - Trojan/TLS - 443",
        "🇫🇷 57 - FR - Trojan/WS/TLS/UTLS - 443",
        "🇺🇸 61 - US - Trojan/WS/TLS/UTLS - 443",
        "🇳🇱 4 - NL - VLESS/REALITY/PBK/SID/VISION - 40443",
        "🇸🇪 6 - SE - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇷🇺 15 - RU - VLESS/TLS/VISION/UTLS - 443",
        "🇺🇸 14 - US - VLESS/REALITY/PBK/VISION - 443",
        "🇺🇸 18 - US - VLESS/GRPC/TLS/UTLS - 443",
        "🇺🇸 1 - US - VMess/WS/TLS - 8444",
        "🇺🇸 3 - US - VMess/WS/TLS - 443",
        "🇺🇸 6 - US - VMess/TLS - 10086",
        "🇺🇸 5 - US - VMess/TLS/UTLS - 10086"
      ],
      "url": "https://www.gstatic.com/generate_204",
      "interval": 180,
      "tolerance": 50
    }
  ],
  "rule-providers": {
    "geosite-malware": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-malware.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
    },
    "geosite-phishing": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-phishing.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt"
    },
    "geosite-cryptominers": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-cryptominers.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.txt"
    },
    "geosite-ads": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-ads.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
    },
    "geosite-ir": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-ir.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
    },
    "geoip-ir": {
      "type": "http",
      "format": "text",
      "behavior": "ipcidr",
      "path": "./ruleset/geoip-ir.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
    }
  },
  "rules": [
    "GEOIP,lan,DIRECT,no-resolve",
    "NETWORK,udp,REJECT",
    "RULE-SET,geosite-malware,REJECT",
    "RULE-SET,geosite-phishing,REJECT",
    "RULE-SET,geosite-cryptominers,REJECT",
    "RULE-SET,geosite-ads,REJECT",
    "RULE-SET,geosite-ir,DIRECT",
    "RULE-SET,geoip-ir,DIRECT",
    "MATCH,✅ Anonymous Multi"
  ],
  "ntp": {
    "enable": true,
    "server": "time.cloudflare.com",
    "port": 123,
    "interval": 30
  }
}